apache:
    image: ba/zurmo_apache
    ports: 
        - "80:80"
    volumes_from:
        - application
        - mysql
    links:
        - mysql
        - mysql:db

application:
    image: ba/zurmo_app

mysql:
    image: icclabcna/zurmo_mysql
